services:
  postgres_students:
    image: postgres
    container_name: postgres_students
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres_db_students:/var/lib/postgresql/data

  node_students:
    container_name: node_students
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_students
    env_file:
      - back-end/.env
    
volumes:
  postgres_db_students: